default:
  LOG_LEVEL: "info"
  DEEPSEEK_API_URL: "https://api.deepseek.com/v1"
  ARK_API_URL: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
  ARK_BASE_URL: "https://ark.cn-beijing.volces.com/api/v3"
  DASHSCOPE_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
  QWEN_API_URL: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  OPENIAI_BASE_URL: "https://api.qhaigc.net"
  OPENIAI_API_KEY: ""
  # baichaun
  BAICHUAN_API_URL: https://api.baichuan-ai.com/v1/chat/completions
  BAICHUAN_BASE_URL: https://api.baichuan-ai.com/v1/
  REDIS_HOST: 118.190.155.195
  REDIS_PORT: 6399
  REDIS_DB: 15
  REDIS_AUTH: "Xlys!@#456qwe"
  score_threshold: 1.75
  rerank: false
  embedding_model: "doubao"
  LOG_REDIS_HOST: "logredis.redis.zhangbei.rds.aliyuncs.com"
  LOG_REDIS_PORT: 6379
  LOG_REDIS_DB: 4
  LOG_REDIS_AUTH: "Xlys!@#456qwe"
  min_connections: 1  # 最小连接数
  max_connections: 10  # 最大连接数
  socket_connect_timeout: 15.0  # 连接超时时间
  socket_timeout: 5.0  # 等待超时时间
  max_idle_time: 60  # 最大空闲时间
  env_version: "alpha"
  # ES
  ES_HOST: es-cn-8qq47vdfe0005swll.public.elasticsearch.aliyuncs.com
  ES_PORT: 9200
  ES_USER: elastic
  ES_AUTH: fh6u65tPxSa@fbcv1pM
  IS_LOCAL: false
  chat_history_num: 8
  CHUNK_SIZE: 2
  special_punctuation: '▢|▶|❗|📞'
  USE_BGE_CODE: false
  USE_RANK: true

  # emr

  # videoagent
  IMAGE_GENERATE_MODEL: doubao-seedream-4-0-250828
  IMAGE_DESCRIBE_MODEL: doubao-1-5-vision-pro-32k-250115
  VIDEO_GENERATE_MODEL: "doubao-seedance-1-0-pro-250528"
  QWEN_IMAGE_DESCRIBE_MODEL: "qwen-vl-max"
  QWEN_IMAGE_DESCRIBE_FLASH_MODEL: "qwen3-vl-flash"
  QWEN_IMAGE_GENERATE_MODEL: "wan2.2-t2i-plus" #通义万相2.2-文生图-Plus
  QWEN_VIDEO_GENERATE_MODEL: "wan2.2-i2v-plus" #通义万相2.2-图生视频-Plus
  OCR_MODEL: qwen-vl-ocr # 效果不如qwen3-vl

  # text model
  DOUBAO_TEXT_MODEL: doubao-1.5-pro-32k-250115
  BAICHUAN_TEXT_MODEL: Baichuan-M2-Plus
   
  # archives
  is_local_file: True
  # 
  debug_mode: false
  # jwt blacklist 
  BLACKLIST: []
  JWT_SECRET: "ZH8JWuMtyyVZWI11/jTxNzYqVsltSGM85lTovOMGPChqomVwnS0jvJI6Ohba5mfkDYevYOlCTzqMpwXKG12/w=="